version: '3.8'
services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '${GRAFANA_PORT}:${GRAFANA_PORT}'
    volumes:
      - ./grafana/grafana_data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    networks:
      - iot_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - grafana
    environment:
      - NGINX_PORT=${NGINX_PORT}
      - GRAFANA_PORT=${GRAFANA_PORT}
    ports:
      - "8080:80" # Change 8080 to any host port you want
    networks:
      - iot_network

  flask:
    build: 
      context: ./server
      dockerfile: Dockerfile.flask
    environment:
      - FLASK_PORT=${FLASK_PORT}
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    networks:
      - iot_network

  ngrok:
    image: wernight/ngrok
    depends_on:
      - flask
    command: /bin/sh -c "ngrok authtoken $$NGROK_TOKEN && ngrok http flask:$$FLASK_PORT"
    environment:
      - NGROK_TOKEN=${NGROK_TOKEN1}
      - FLASK_PORT=${FLASK_PORT}
    ports:
      - "5050:4040"
    networks:
      - iot_network

  ngrok2:
    image: wernight/ngrok
    depends_on:
      - grafana
    command: /bin/sh -c "ngrok authtoken $$NGROK_TOKEN && ngrok http nginx:$$NGINX_PORT"
    environment:
      - NGROK_TOKEN=${NGROK_TOKEN2}
      - NGINX_PORT=${NGINX_PORT}
    ports:
      - "4040:4040"
    networks:
      - iot_network

# volumes:
#   grafana_data: {}

networks:
  iot_network: