FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy the application and the requirements file
COPY . /app/

# Install the requirements
RUN pip install --no-cache-dir -r requirements.txt

# Command to run the application
CMD ["python", "app.py"]
