FROM python:3.10

# Set working directory
WORKDIR /app

# Copy the application and the requirements file
COPY . /app/

# Install the requirements
RUN pip install -r requirements.txt
RUN apt-get -y update && apt-get -y upgrade && apt-get install -y --no-install-recommends ffmpeg

# Command to run the application
CMD ["python", "app.py"]
