FROM python:3.10-slim-bullseye

# Set working directory
WORKDIR /app

RUN apt update
RUN apt install procps curl -y

RUN alias ll='ls -alhF'

# Copy the application and the requirements file
COPY . /app/

# Install the requirements
RUN pip install --no-cache-dir -r requirements.txt
RUN apt-get -y update && apt-get -y upgrade && apt-get install -y --no-install-recommends ffmpeg

# Command to run the application
CMD ["python", "app.py"]
